name: Sync Image to Aliyun  Example
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Git pull
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
 
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-7nwwtft5dxxic52w.cn-shenzhen.personal.cr.aliyuncs.com #注意这里
        username: 星儿的流星雨
        password: 20020731hunter
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://elasticsearch/elasticsearch:8.6.0 docker://crpi-7nwwtft5dxxic52w.cn-shenzhen.personal.cr.aliyuncs.com/openmetadata_hunter/elasticsearch
      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
 
